server {
	listen 443 ssl;
	server_name mabi-nak.42.fr;
	
	ssl_certificate /etc/nginx/certs/certificate.crt;
	ssl_certificate_key /etc/nginx/certs/certificate.key;
	
	root /var/www/html;
	index index.php index.html;

	location / {
	    try_files $uri $uri/ /index.php?$args;
	}

	location ~ \.php$ {
	fastcgi_pass wordpress:9000;
	include fastcgi_params;
	fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
}
}

